apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-playground.fullname" . }}
  namespace: {{ include .Values.namespaceOverride }}
  labels:
{{ include "security-playground.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "security-playground.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
